gcloud compute networks create net-03 --project=core-port-327608 --subnet-mode=custom --mtu=1460 --bgp-routing-mode=regional && gcloud compute networks subnets create uscentral1 --project=core-port-327608 --range=10.128.0.0/20 --network=net-03 --region=us-central1 && gcloud compute networks subnets create uscentral2 --project=core-port-327608 --range=10.186.0.0/20 --network=net-03 --region=europe-central2 &&

gcloud compute firewall-rules create first-rule --network net-03 --allow tcp,udp,icmp --source-ranges 0.0.0.0/0 &&
gcloud compute firewall-rules create rule-two --network net-03 --allow tcp:22,tcp:3389,icmp &&

gcloud compute instances create my-vm-us2 --project=core-port-327608 --zone=us-central1-a --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=uscentral1 --maintenance-policy=MIGRATE --service-account=655757112834-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=my-vm-us2,image=projects/debian-cloud/global/images/debian-10-buster-v20210916,mode=rw,size=10,type=projects/core-port-327608/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any &&

gcloud compute instances create my-vm-us3 --project=core-port-327608 --zone=us-central1-a --machine-type=e2-medium --network-interface=network-tier=PREMIUM,subnet=uscentral1 --maintenance-policy=MIGRATE --service-account=655757112834-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --create-disk=auto-delete=yes,boot=yes,device-name=my-vm-us3,image=projects/debian-cloud/global/images/debian-10-buster-v20210916,mode=rw,size=10,type=projects/core-port-327608/zones/us-central1-a/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any &&

gcloud beta network-management connectivity-tests create my-vm-us3-my-vm-us2 --destination-instance=projects/core-port-327608/zones/us-central1-a/instances/my-vm-us2 --destination-port=80 --protocol=TCP --source-instance=projects/core-port-327608/zones/us-central1-a/instances/my-vm-us3 --project=core-port-327608 &&

gcloud beta network-management connectivity-tests create my-vm-eu2-my-vm-us --destination-instance=projects/core-port-327608/zones/us-central1-a/instances/my-vm-us --destination-port=80 --protocol=TCP --source-instance=projects/core-port-327608/zones/europe-west3-b/instances/my-vm-eu2 --project=core-port-327608